name: Cron Statistics

on:
  schedule:
    # 定时触发的 Cron 表达式，例如 "0 9 * * *" 表示每天上午 9 点触发
    - cron: '40 22 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # 如果你的脚本需要其他依赖，在这里安装
        pip install -r requirements.txt

    - name: Get Current Time
      id: date
      run: |
        # 设置环境变量 CURRENT_DATE 为当前时间
        echo "CURRENT_DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Run Script
      run: |
        python stats-github-project.py --only_json > ./data/stats-${{ env.CURRENT_DATE }}.json

    - name: Push JSON Result to Data Directory
      run: |
        # 假设脚本执行后的输出是一个名为 result.json 的文件
        # git config --global user.name 'elliotxx'
        # git config --global user.email '951376975@qq.com'
        # 添加文件到暂存区
        git add ./data/
        # 提交并推送到 origin 的当前分支
        git commit -m "Add stats result for ${{ env.CURRENT_DATE }}"
        git push origin HEAD:${{ github.ref }}
      env:
        GIT_PUSH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
